---
title: "MCMC Metrop Code"
author: "Benjamin Lutz"
date: "5/11/2022"
output: html_document
---

The link to this example is: https://khayatrayen.github.io/MCMC.html

Here's an example.

```{r}
knitr::opts_chunk$set(echo = TRUE)

 
trueA <- 5
trueB <- 0
trueSd <- 10
sampleSize <- 31
 
# create independent x-values 
x <- (-(sampleSize-1)/2):((sampleSize-1)/2)
# create dependent values according to ax + b + N(0,sd)
y <-  trueA * x + trueB + rnorm(n=sampleSize,mean=0,sd=trueSd)
 
plot(x,y, main="Test Data")
```

We first fit our model as follows.

\begin{equation*}
  \hat{y} = a*x + b + N(0, sigma2)
\end{equation*}

and the goal is to get values similar to the original parameter values.

**Derive the likelihood function**

```{r}
# param is a vector of parameter values for A, B, and Sd, respectively, drawn from the sample data. 
likelihood <- function(param){
    a = param[1]
    b = param[2]
    sd = param[3]
     
    pred = a*x + b
    singlelikelihoods = dnorm(y, mean = pred, sd = sd, log = T)
    sumll = sum(singlelikelihoods)
    return(sumll)   
}
 
# Example: plot the likelihood profile of the slope a
slopevalues <- function(x){return(likelihood(c(x, trueB, trueSd)))}
slopelikelihoods <- lapply(seq(3, 7, by=.05), slopevalues )
plot (seq(3, 7, by=.05), slopelikelihoods , type="l", xlab = "values of slope parameter a", ylab = "Log likelihood")
```

**Derive the prior**

```{r}
# param is a vector of parameter values for A, B, and Sd, respectively, drawn from the sample data. 
prior <- function(param){
    a = param[1]
    b = param[2]
    sd = param[3]
     
    pred = a*x + b
    singlePrior.a = dnorm(y, mean = a, sd = sd, log = T)
    sumll = sum(singlelikelihoods)
    return(sumll)   
}
```


```{r}
posterior <- function(param){
   return (likelihood(param) + prior(param))

}
```



```{r}
proposalfunction <- function(param){
    return(rnorm(3,mean = param, sd= c(0.1,0.5,0.3)))
}
 
run_metropolis_MCMC <- function(startvalue, iterations){
    chain = array(dim = c(iterations+1,3))
    chain[1,] = startvalue
    for (i in 1:iterations){
        proposal = proposalfunction(chain[i,])
         
        probab = exp(posterior(proposal) - posterior(chain[i,]))
        if (runif(1) < probab){
            chain[i+1,] = proposal
        }else{
            chain[i+1,] = chain[i,]
        }
    }
    return(chain)
}
 
startvalue = c(4,0,10)
chain = run_metropolis_MCMC(startvalue, 10000)
 
burnIn = 5000
acceptance = 1-mean(duplicated(chain[-(1:burnIn),]))
```